### ISSUE TITLE
Storage migration research and pallet versioning

### ISSUE THREAD

**Issue by Janislav** [chainflip-io/chainflip-backend#1059]
# Describtion

In the future, we probably have to perform storage migration. To do that we've to understand how versioning of pallets and storage migration plays together. The use-case we've to understand is how does storage migration works if someone has to sync the whole node from scratch.

# Todos
- [ ] Figure out how storage migration works
- [ ] Figure out how pallet versioning works
- [ ] Answer the question: Do we need to keep the version-specific migration code for later node syncs?
- [ ] Document versioning and storage migration for later use
