### ISSUE TITLE
[Tracker] State Chain Sanity Checks for Perseverance launch

### ISSUE THREAD

**Issue by dandanlen** [chainflip-io/chainflip-backend#2188]
### Description

Before we start our public testnet I would like us to do a mini-audit of our pallets to reassure ourselves that there are no obvious holes. 

Pallets (not including Ibiza):
- [x] #2190
- [x] #2191
- [x] #2192
- [x] #2193
- [x] #2194
- [x] #2195
- [x] #2196
- [x] #2197
- [x] #2198
- [x] #2199
- [x] #2200
- [x] #2201
- [x] #2202
- [x] #2203

Runtime:
- [x] #2204
- [x] #2205
- [x] #2206
- [x] #2207
- [x] #2208
- [x] #2209
- [x] #2302 
- [x] #2307

A rough checklist:

- [ ] Unit tests:
	- [ ] Are they complete? What is not covered? Does it need to be?
	- [ ] Do the mocks make sense?
- [ ] Benchmarks: 
	- [ ] Are they correctly parameterised?
- [ ] Weights:
	- [ ] Has the weights file been generated?
	- [ ] Are the weights connected to the correct extrinsics / hooks / whatever?
- [ ] Extrinsics: 
	- [ ] Are the origins restricted correctly? 
	- [ ] Are they documented?
- [ ] Storage:
	- [ ] Is the storage hasher reasonable?
	- [ ] Are we iterating over storage anywhere? Do we need to?
- [ ] General:
	- [ ] Is the logic sound and clearly laid out in the code? 
	- [ ] Are panics correctly justified / documented?
	- [ ] Are traits clearly documented?
