### ISSUE TITLE
[Tracker] Polkadot initialisation

### ISSUE THREAD

**Issue by dandanlen** [chainflip-io/chainflip-backend#2495]
### Description

As discussed, in order to set up a polkadot network we need the following:

- [ ] Fund the AggKey proxy account
	Can be a script or binary to transfer funds, or pre-funded via chainspec.
- [x] Governance call: create polkadot vault
	-> triggers pure proxy transaction
- [x] Governance call: set polkadot vault address (in environment pallet)

@ramizhasan111 can you split these out into separate issues/PRs please.
