### ISSUE TITLE
[TRACKER]: Bitcoin blockers

### ISSUE THREAD

**Issue by dandanlen** [chainflip-io/chainflip-backend#3100]
### Description

Compiling a list of outstanding blocking tasks required to be able to include bitcoin in the next release, for visibility.

- [ ] Key Handover needs to be requested from the state chain
        #3109
- [ ] Address reuse issue
	TODO RAISE ISSUE
- [ ] Signing with multiple keys
	#2948
- [ ] Address encoding
	#3063 

FYI. @ramizhasan111 @martin-chainflip @msgmaxim
