### ISSUE TITLE
[CH-725] slashing

### ISSUE THREAD

**Issue by Janislav** [chainflip-io/chainflip-backend#476]
## Introduction

Currently, we have a dummy implementation for slashing in the reputation pallet. We want to replace this with a real implementation in the Flip pallet which actually burns some Flip of a validator if he misbehaves.

## Burning

Slashing is based on the number of blocks a validator was "offline" (the definition for offline is based on several conditions the reputation pallet takes care of). The burn is based on the following assumptions:

- SlashingRate = n% of MAB
- BlocksPerDay = 86400/blocktime
- Burn = SlashingRate / BlocksPerDay

## Tasks

- [x] Move slashing trait to global traits
- [x] Implement the slashing trait in Flip pallet and burn Flip there
- [x] Use the slashing trait implemented in the Flip pallet in the reputation pallet
- [x] Make the SlashingRate changeable via governance extrinsic
- [x] Use the actual blocktime
