### ISSUE TITLE
[CH-2218] Tracking issue for keygen unit tests

### ISSUE THREAD

**Issue by msgmaxim** [chainflip-io/chainflip-backend#677]
This is not an exhaustive list, but it should roughly match the tests we had in the old protocol.

- [x] If a keygen ceremony expires *before* a keygen request, we should report the initiators of the ceremony.
- [x] If a keygen ceremony expires *after* a keygen request, we should report the parties that failed to send current stage data in time.
- [x] Message delaying. (Data for any stage that arrives one stage too early should be properly delayed and processed after the stage transition is made.
- [x] Ignore duplicate keygen request
- [x] Ignore a keygen request if we are not participating
- [x] Keygen data from an unknown validator should be ignored (but we should still delay it in case we don't have the list of  participants yet).
- [x] If one of more parties (are thought to) broadcast data inconsistently, the ceremony should be aborted and all faulty parties should be reported.
- [x] If one or more parties submit invalid data (e.g. secret shares are invalid w.r.t the party commitments), the ceremony should be aborted and all faulty parties should be reported. 
- [x] Keygen aborts if the resulting key is not compatible with the contract 
- [x] Should report the sender of an invalid commitment 
- [x] Should ignore a keygen request that has a list of signers that contains a duplicate id
- [ ] Unit Test for `[SC-2387] CFE should keep track of all past ceremony_id`.
